@component('mail::message')
# Hi there!

There is a new lead from your Google Ads Lead Extension. The information provided by the user is shown in the table below.

@component('mail::table')
| Key | Value |
| :--- | :--- |
@foreach ($lead->getRequest()['user_column_data'] as $data)
| **{{ $data['column_name'] }}** | **{{ $data['string_value'] }}** |
@endforeach
@endcomponent

Kind regards,<br>
{{ config('app.name') }}

@component('mail::subcopy')
    This message was automaticly generated by the Google Ads Lead Extension Package brought to you by <a href="https://marshmallow.dev">Marshmallow</a>.
@endcomponent
@endcomponent
